output_dir: checkpoints

data:
  raw_dir: data/raw
  labels_excel: data/labels.xlsx

model:
  max_ocr_len: 64
  max_hp_len: 64
  transformer_dim: 256
  n_heads: 4
  n_layers: 2
  decoder_layers: 2
  dropout: 0.1
  pretrained_cnn: true

training:
  epochs: 10
  batch_size: 8
  lr: 0.001
  val_ratio: 0.1
  amp: false
  hp_loss_weight: 1.0
